### ISSUE TITLE
does it work with 3.1.1?

### ISSUE THREAD

**Issue by testing7771** [garrynewman/Control4.Jailbreak#1]
does it work with 3.1.1?

**Comment by garrynewman** [comment]
No, I haven't updated to 3.1.1 yet

**Comment by testing7771** [comment]
thanks for quick reply. any ETA for 3.1.1? or manual steps?

**Comment by garrynewman** [comment]
I don't know. Apparently you can log in via ssh in composer and change the default password back to t0talc0ntr0l4! (using "passwd t0talc0ntr0l4!"). If you can do that then this method should still work.

The sticking point is whether you can use the new Composer SSH terminal without being a dealer.
