### ISSUE TITLE
Will this work on 3.1.2?

### ISSUE THREAD

**Issue by zuhair68** [garrynewman/Control4.Jailbreak#2]
Will this work on 3.1.2?

**Comment by garrynewman** [comment]
It won't work on 3.1.2 right now unless you log in manually via system manager and change the username and password back to root/t0talc0ntr0l4! - at which point it should technically work fine.

I will update it at some point - but I've stayed on 3.1.0 right now.

**Comment by zuhair68** [comment]
Anyone tried it with 3.1.2?

**Comment by garrynewman** [comment]
It should work on 3.1.2 and 3.1.3 now.
