### ISSUE TITLE
Upgrade inquiry

### ISSUE THREAD

**Issue by zuhair68** [garrynewman/Control4.Jailbreak#3]
This actually an inquiry not an issue.

I want to make sure before I start, these will be my steps, I'm currently on 3.1.0 (not patched):

1. Upgrade the controller to 3.1.3
2. Download and install 3.1.3 Composer Pro
3. Run the jailbreak

Correct, right?

**Comment by garrynewman** [comment]
Yeah that's right

**Comment by zuhair68** [comment]
When patching the controller I get this message:

**Copying To Director
Skipping director patch because we're not connected**

jailbreak user and password is created

**Comment by garrynewman** [comment]
When you press Patch Controller is the IP in the address the IP of your controller?

**Comment by zuhair68** [comment]
Yes, it's the correct IP

**Comment by garrynewman** [comment]
I see the problem - have uploaded a new version (2.1) here: https://github.com/garrynewman/Control4.Jailbreak/releases/tag/v2

**Comment by zuhair68** [comment]
All went fine when connecting, I get this message

<img width="535" alt="Screen Shot 2020-06-03 at 5 38 24 PM" src="https://user-images.githubusercontent.com/13981990/83650637-3b46fa80-a5c1-11ea-830a-d5a9111d49d9.png">

**Comment by garrynewman** [comment]
Have you restarted it?

**Comment by zuhair68** [comment]
I restarted the controller again, the same problem. maybe I should redo the whole thing after cleaning the PC from all Composer version?

**Comment by garrynewman** [comment]
IMO the fact that you can connect via System Manager says that there's nothing wrong with composer - but it's worth a go.

My gut tells me that the certificate isn't right on the director. It might be worth trying to re-apply it, failing that - if you send me your Certs folder (next to the jailbreak exe) I'll take a look to see if there's anything weird. You can email to garrynewman@gmail.com

**Comment by zuhair68** [comment]
Folder sent by email.

**Comment by zuhair68** [comment]
Same problem.

Here's what I did:

1. I uninstalled all Composers version
2. Deleted \AppData\Roaming\Control4
3. Deleted \Program Files (x86)\Control4
4. Reboot the PC
5. Reinstalled Composer 3.1.3
6. Run the Jailbreak (all steps are successful) 
7. Reboot the Controller

**Comment by gniting** [comment]
Watching this thread in case there's a key step missing/needed. I'll wait for a resolution before trying the new version on my 3.1.0 system.

**Comment by garrynewman** [comment]
Thanks for the Certs folder @zuhair68, I can't see anything that would explain the error. 

It might be time to start looking at log files on the director to see why it's rejecting the connection. If you want to send me the log I can take a look at it.

1. Open System Manager, connect to the director
2. Try to connect via composer
3. Go to the Logging page on System Manager and email me the director log if possible

**Comment by zuhair68** [comment]
Log file is sent by email.

**Comment by zuhair68** [comment]
This error is logged on every connection attempt:

**ERROR: No obsolete device public key to remove**

**Comment by garrynewman** [comment]
Alright so here's the situation as far as I can see it

* Client is trying to connect
* Server is rejecting it
* Your Server Certificate is the same as mine, but with your own generated version at the end
* Your Composer and System Manager are trying to connect - so they have no issues
* All your versions are the same as mine

I'm afraid without access to your server and side by side comparing your files with mine, I'm pretty stuck here.

What's the history of your box? How have you jailbroken it before?

**Comment by zuhair68** [comment]
No, it was running 3.1.0 unpatched. Will Teamwork be ok?

Sent from my iPhone

On 3 Jun 2020, at 10:18 PM, Garry Newman <notifications@github.com> wrote:

﻿

Alright so here's the situation as far as I can see it

  *   Client is trying to connect
  *   Server is rejecting it
  *   Your Server Certificate is the same as mine, but with your own generated version at the end
  *   Your Composer and System Manager are trying to connect - so they have no issues
  *   All your versions are the same as mine

I'm afraid without access to your server and side by side comparing your files with mine, I'm pretty stuck here.

What's the history of your box? How have you jailbroken it before?

**Comment by zuhair68** [comment]
I mean TeamViewer 😅

Sent from my iPhone

On 3 Jun 2020, at 10:35 PM, Zuhair <zuhair@shafai.org> wrote:

﻿ No, it was running 3.1.0 unpatched. Will Teamwork be ok?

Sent from my iPhone

On 3 Jun 2020, at 10:18 PM, Garry Newman <notifications@github.com> wrote:

﻿

Alright so here's the situation as far as I can see it

  *   Client is trying to connect
  *   Server is rejecting it
  *   Your Server Certificate is the same as mine, but with your own generated version at the end
  *   Your Composer and System Manager are trying to connect - so they have no issues
  *   All your versions are the same as mine

I'm afraid without access to your server and side by side comparing your files with mine, I'm pretty stuck here.

What's the history of your box? How have you jailbroken it before?

**Comment by zuhair68** [comment]
Let me know what suits you, TeamViewer access or send you all the server files.

Regards,

Sent from my iPhone

On 3 Jun 2020, at 10:36 PM, Zuhair <zuhair@shafai.org> wrote:

﻿ I mean TeamViewer 😅

Sent from my iPhone

On 3 Jun 2020, at 10:35 PM, Zuhair <zuhair@shafai.org> wrote:

﻿ No, it was running 3.1.0 unpatched. Will Teamwork be ok?

Sent from my iPhone

On 3 Jun 2020, at 10:18 PM, Garry Newman <notifications@github.com> wrote:

﻿

Alright so here's the situation as far as I can see it

  *   Client is trying to connect
  *   Server is rejecting it
  *   Your Server Certificate is the same as mine, but with your own generated version at the end
  *   Your Composer and System Manager are trying to connect - so they have no issues
  *   All your versions are the same as mine

I'm afraid without access to your server and side by side comparing your files with mine, I'm pretty stuck here.

What's the history of your box? How have you jailbroken it before?

**Comment by garrynewman** [comment]
If downloading and sending me the server files is within your abilities, we can definitely try that first

**Comment by zuhair68** [comment]
Thank you for your support and patient, which folders shall I send?


On 4 Jun 2020, at 9:01 AM, Garry Newman <notifications@github.com<mailto:notifications@github.com>> wrote:



If downloading and sending me the server files is within your abilities, we can definitely try that first

**Comment by zuhair68** [comment]
Server files sent by email.
Thank you for your support & patience.

**Comment by gniting** [comment]
Could either of you please update here when you have additional info? Would like to learn as much as I can before jumping in. Thanks!

**Comment by zuhair68** [comment]
It is still giving the same error, I sent the files for @garrynewman to check.

**Comment by zuhair68** [comment]
I tried the Jailbreak tool from a third PC that didn't have Composer installed earlier, the same problem. **Could not connect to Director at xxx.xxx.xxx.xxx**

**Comment by zuhair68** [comment]
Update: I used the Device Image Updater to install a fresh 3.1.3 then used the Jailbreak tool. It worked like a charm! I will have a deep sleep tonight.
Garry, thank you for time and effort.

**Comment by gniting** [comment]
@zuhair68 whats the “device image updater” and is it for controller or composer? If you can provide some steps, that’ll be awesome. Thanks!

**Comment by gniting** [comment]
Found it...!

**Comment by garrynewman** [comment]
> **Update:** I used the Device Image Updater to install a fresh 3.1.3 then used the Jailbreak tool. It worked like a charm! I will have a deep sleep tonight!
> Garry, thank you for your time and effort.

Great! Glad to hear it all worked out in the end!

**Comment by zuhair68** [comment]
> Found it...!

Make sure to have a backup of your project, I did the Jailbreak before restoring the project.

**Comment by gniting** [comment]
I'll make a fresh backup, that's not a problem. But if I blank out the controller, then it'll lose all its settings, including network settings. Then, in order to connect to it again, do I need to directly wire into it and set IP address, etc?

**Comment by zuhair68** [comment]
System Manager will discover the device, and to prevent that you assign a static IP in your router using the current IP so when it boots up it will use the reserved IP.

**Comment by gniting** [comment]
got it, thanks!

**Comment by zuhair68** [comment]
> got it, thanks!

How did it go?

**Comment by gniting** [comment]
I haven't done it yet. If I blank out controller, then won't I run into a registration issue to get the controller registered with Control4? Right now, I have a "patched" 3.10x system. I used the last version of Garry's tool to gain access. I believe you did not have a patched system prior. So, I am now waiting to see if someone who had a patched system before, can successfully use the new version of Garry's tool.

Yes, I am being overly paranoid, but I don't want to lose access.
